### ISSUE TITLE
java.nio.file.AccessDeniedException s3a://datalake/deltatables/***/_symlink_format_manifest

### ISSUE THREAD

**Issue by adicirstei** [arezamoosavi/AcidOnSpark-ETL#4]
Hi!

I'm totally new to spark/hive/airflow and I ran into an error while running the `spark_create_table.py`. 

It seems it's not able to access the `_symlink_format_manifest` on minio. For me it's strange as it just created it at the previous step. 

```
Traceback (most recent call last):
  File "/opt/airflow/dags/etl/spark_create_table.py", line 31, in <module>
    spark.sql(sql_delta_table)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 723, in sql
  File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 117, in deco
pyspark.sql.utils.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Got exception: java.nio.file.AccessDeniedException s3a://datalake/deltatables/employees/_symlink_format_manifest: getFileStatus on s3a://datalake/deltatables/employees/_symlink_format_manifest: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 1736C1CB94490DFC; S3 Extended Request ID: null), S3 Extended Request ID: null:403 Forbidden)
```

BTW: I am able to run:

```py
spark.sql("SELECT * FROM delta.`s3a://datalake/deltatables/employees/` ").show()
```

I really appreciate the work you do. 

Thanks a lot!
Adrian

**Comment by adicirstei** [comment]
Solved.

I finally noticed there is another accessKey for the hive. Maybe you should make a note in the README that one needs to create the two access keys and secrets for spark and hive on minio.
